version: "3.8"

services:
  mysql:
    container_name: mysql8_fastapi
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fastapi
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    tty: true
    # mbind: Operation not permitted 防止
    # https://selfnote.work/20210315/programming/mysql-docker-error-mbind/
    cap_add:
      - SYS_NICE

  api:
    depends_on:
      - mysql
    container_name: fastapi_python310
    volumes:
      - ./app:/app
    build:
      context: .
      dockerfile: ./.docker/fastapi/Dockerfile
    env_file:
      - .env.local
    ports:
      - 80:80
    # 修正を即時反映する
    command: /start-reload.sh
